### ISSUE TITLE
The testsuite is failing

### ISSUE THREAD

**Issue by jvoisin** [magne4000/festival#47]
```bash
jvoisin@mim 13:42 ~/Dev/festival python3 festival.py --check                                                                               U [master] git:festival
'settings.cfg' file does not exists, it will be created.
You just need to fill the following form

Path to directory containing musics: /tmp
OK
```

```python
jvoisin@mim 13:42 ~/Dev/festival python3 test.py                                                                                           U [master] git:festival
/home/jvoisin/.local/lib/python3.5/site-packages/flask/config.py:12: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
.EE........
======================================================================
ERROR: test_get_album_list (__main__.FestivalTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 265, in test_get_album_list
    rv = self.app.get('/rest/getAlbumList.view?type=newest')
  File "/home/jvoisin/.local/lib/python3.5/site-packages/werkzeug/test.py", line 778, in get
    return self.open(*args, **kw)
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/testing.py", line 108, in open
    follow_redirects=follow_redirects)
  File "/home/jvoisin/.local/lib/python3.5/site-packages/werkzeug/test.py", line 751, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "/home/jvoisin/.local/lib/python3.5/site-packages/werkzeug/test.py", line 668, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/home/jvoisin/.local/lib/python3.5/site-packages/werkzeug/test.py", line 871, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jvoisin/Dev/festival/festivallib/request.py", line 239, in wrapper
    return func(Typed(stype), *arg, **kwargs)
  File "/home/jvoisin/Dev/festival/api/subsonic.py", line 372, in album_list
    'album': [format_album(album, child=True) for album in albums]
  File "/home/jvoisin/Dev/festival/api/subsonic.py", line 372, in <listcomp>
    'album': [format_album(album, child=True) for album in albums]
  File "/home/jvoisin/Dev/festival/api/subsonic.py", line 91, in format_album
    'id': format_album_id(album.id),
AttributeError: 'result' object has no attribute 'id'

======================================================================
ERROR: test_get_album_list2 (__main__.FestivalTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 327, in test_get_album_list2
    rv = self.app.get('/rest/getAlbumList2.view?type=newest')
  File "/home/jvoisin/.local/lib/python3.5/site-packages/werkzeug/test.py", line 778, in get
    return self.open(*args, **kw)
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/testing.py", line 108, in open
    follow_redirects=follow_redirects)
  File "/home/jvoisin/.local/lib/python3.5/site-packages/werkzeug/test.py", line 751, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "/home/jvoisin/.local/lib/python3.5/site-packages/werkzeug/test.py", line 668, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/home/jvoisin/.local/lib/python3.5/site-packages/werkzeug/test.py", line 871, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jvoisin/.local/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jvoisin/Dev/festival/festivallib/request.py", line 239, in wrapper
    return func(Typed(stype), *arg, **kwargs)
  File "/home/jvoisin/Dev/festival/api/subsonic.py", line 384, in album_list2
    'album': [format_album(album) for album in albums]
  File "/home/jvoisin/Dev/festival/api/subsonic.py", line 384, in <listcomp>
    'album': [format_album(album) for album in albums]
  File "/home/jvoisin/Dev/festival/api/subsonic.py", line 91, in format_album
    'id': format_album_id(album.id),
AttributeError: 'result' object has no attribute 'id'

----------------------------------------------------------------------
Ran 11 tests in 0.520s

FAILED (errors=2)
zsh: exit 1     python3 test.py
```

**Comment by jvoisin** [comment]
I still have this issue, even on the `dev` branch.

**Comment by magne4000** [comment]
Due to different versions of SQLAlchemy (0.8.1 vs 1.0.12)

**Comment by magne4000** [comment]
Fixed on dev branch
